- name: Insights events
  hosts: localhost
  sources:
    - redhat.insights_eda.insights:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: match vulnerability event
      condition: |-
        event.payload.application == "vulnerability"
        and event.payload.event_type in [
          "new-recommendation",
          "any-cve-known-exploit",
          "new-cve-cvss",
          "new-cve-severity",
          "new-cve-security-rule"
        ]
      action:
        run_job_template:
          name: "Security | RHEL | Handle Insights Events"
    - name: match compliance-below-threshold event
      condition: |- 
        event.payload.application == "compliance"
        and event.payload.event_type == "compliance-below-threshold"
      action:
        run_job_template:
          name: "Security | RHEL | Handle Insights Events"
          job_args:
            extra_vars:
              host: "{{ event.payload }}"
    - name: match malware detected event
      condition: |-
        event.payload.application == "malware-detection"
        and event.payload.event_type == "detected-malware"
      action:
        run_job_template:
          name: "Security | RHEL | Insights Detected Malware"
          job_args:
            extra_vars:
              host: "{{ event.payload }}"
