- name: Insights events
  hosts: localhost
  sources:
    - redhat.insights_eda.insights:
  rules:
    - name: match vulnerability event
      condition: |-
        event.payload.application == "vulnerability"
        and event.payload.event_type in [
          "new-recommendation",
          "any-cve-known-exploit",
          "new-cve-cvss",
          "new-cve-severity",
          "new-cve-security-rule"
        ]
      action:
        run_job_template:
          name: insights_events.yml