---
- name: Scan all hosts for malware with Insights
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Ensure insights-client is installed on the host
      ansible.builtin.dnf:
        name: 
          - insights-client
          - yara
        state: latest

    - name: Ensure /etc/insights-client/malware-detection-config.yml is not set to test
      ansible.builtin.lineinfile:
        path: /etc/insights-client/malware-detection-config.yml
        search_string: "test_scan: true"
        line: "test_scan: false"

    - name: Begin Insights scan
      ansible.builtin.command:
        cmd: insights-client --collector malware-detection
