---
- name: Scan all hosts for malware with Insights
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Ensure insights-client is installed on the host
      ansible.builtin.dnf:
        name: insights-client
        state: latest

    - name: Begin Insights scan
      ansible.builtin.command:
        cmd: insights-client --collector malware-detection
